### ISSUE TITLE
训练PPO时报错

### ISSUE THREAD

**Issue by nuigdpgf** [ssbuild/rlhf_chatglm#1]
```
The dtype of attention mask (torch.int64) is not bool
Traceback (most recent call last):
  File "/rlhf_chatglm/rlhf/train.py", line 169, in <module>
    trainer.fit(pl_model,
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/ppo_trainer.py", line 244, in fit
    self.make_experience(model,ref_model)
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/ppo_trainer.py", line 783, in make_experience
    metadata = gather_dict({k: v for k, v in batch.items() if k != "input_ids" and k != "attention_mask"})
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/utils/__init__.py", line 173, in gather_dict
    acc[k].extend(obj[k])
AttributeError: 'Tensor' object has no attribute 'extend'. Did you mean: 'expand'?
[rollout 0 / 128]:   0%|                                                                                                                                                            | 0/128 [00:06<?, ?it/s]
root@pbj-dlearn-20-113:/rlhf_chatglm/rlhf# Traceback (most recent call last):
  File "/rlhf_chatglm/rlhf/train.py", line 169, in <module>
    trainer.fit(pl_model,
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/ppo_trainer.py", line 244, in fit
    self.make_experience(model,ref_model)
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/ppo_trainer.py", line 783, in make_experience
    metadata = gather_dict({k: v for k, v in batch.items() if k != "input_ids" and k != "attention_mask"})
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/utils/__init__.py", line 173, in gather_dict
    acc[k].extend(obj[k])
AttributeError: 'Tensor' object has no attribute 'extend'. Did you mean: 'expand'?
Traceback (most recent call last):
  File "/rlhf_chatglm/rlhf/train.py", line 169, in <module>
    trainer.fit(pl_model,
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/ppo_trainer.py", line 244, in fit
    self.make_experience(model,ref_model)
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/ppo_trainer.py", line 783, in make_experience
    metadata = gather_dict({k: v for k, v in batch.items() if k != "input_ids" and k != "attention_mask"})
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/utils/__init__.py", line 173, in gather_dict
    acc[k].extend(obj[k])
AttributeError: 'Tensor' object has no attribute 'extend'. Did you mean: 'expand'?
```
这个错误请问怎么解决，谢谢

**Comment by ssbuild** [comment]
pip list | grep -E "torch|deep"

**Comment by nuigdpgf** [comment]
```
deep-training            0.1.5
deepdiff                 6.3.0
pytorch-lightning        2.0.2
torch                    2.0.1
torchmetrics             0.11.4
```

**Comment by nuigdpgf** [comment]
```
AttributeError: 'Tensor' object has no attribute 'extend'. Did you mean: 'expand'?
----------- <class 'list'> <class 'list'>
----------- <class 'list'> <class 'list'>
----------- <class 'torch.Tensor'> <class 'torch.Tensor'>
```
打印type最后一次是Tensor类型

**Comment by ssbuild** [comment]
> ```
> AttributeError: 'Tensor' object has no attribute 'extend'. Did you mean: 'expand'?
> ----------- <class 'list'> <class 'list'>
> ----------- <class 'list'> <class 'list'>
> ----------- <class 'torch.Tensor'> <class 'torch.Tensor'>
> ```
> 
> 打印type最后一次是Tensor类型

复现不了你这个问题。 拉取代码，删除output 再试试，。

**Comment by nuigdpgf** [comment]
![image](https://github.com/ssbuild/rlhf_chatglm/assets/7640706/29aa50f6-baf0-4aa4-bffc-81e29f1fcecf)
改成 metadata = gather_dict({k: v for k, v in batch.items() if k != "input_ids" and k != "attention_mask" and k!="position_ids"}) 可以继续跑，但又报了下面错误：
```
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
Traceback (most recent call last):
  File "/rlhf_chatglm/rlhf/train.py", line 168, in <module>
    trainer.fit(pl_model,
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/ppo_trainer.py", line 247, in fit
    self.train_loop(
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/ppo_trainer.py", line 370, in train_loop
    self.post_epoch_callback(model=model,ref_model=ref_model)
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/ppo_trainer.py", line 278, in post_epoch_callback
    self.make_experience(model, ref_model)
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/ppo_trainer.py", line 769, in make_experience
    samples = self.generate(model , batch["input_ids"], attention_mask , **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/rl/ppo/ppo_trainer.py", line 661, in generate
    return model.generate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/rlhf_chatglm/rlhf/../models/__init__.py", line 55, in generate
    return self.get_llm_model().generate(*args,**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1565, in generate
    return self.sample(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2648, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by ssbuild** [comment]
需混合精度训练 已fixed
