### ISSUE TITLE
如何加载训练好的sft模型

### ISSUE THREAD

**Issue by nuigdpgf** [ssbuild/rlhf_chatglm#2]
请问ppo阶段如何加载之前训练好的通过p-tuning v2微调的sft模型，谢谢

**Comment by ssbuild** [comment]
https://github.com/ssbuild/chatglm_finetuning/blob/f529b3e6df84a66365d532140dc3d9b38b8edfb6/infer_finetuning.py#L60

1.直接把微调权重转换成hf格式 ,  这样就形成了一个新的类似官方的权重。
2然后修改  rlhf_config.py  
'model_name_or_path': '/data/nlp/pre_models/torch/chatglm/chatglm-6b',
'config_name': '../models/config/config.json',
'tokenizer_name': '/data/nlp/pre_models/torch/chatglm/chatglm-6b',
改成新的权重即可。

**Comment by nuigdpgf** [comment]
```
Traceback (most recent call last):
  File "/chatglm_finetuning/infer_finetuning.py", line 10, in <module>
    from models import MyTransformer,ChatGLMTokenizer,setup_model_profile, ChatGLMConfig,LoraArguments
ImportError: cannot import name 'setup_model_profile' from 'models' (/chatglm_finetuning/models.py)
```
您好改完后报错了

**Comment by ssbuild** [comment]
> setup_model_profile

更新一下程序， setup_model_profile 是在的。

**Comment by nuigdpgf** [comment]
是的，我的程序是很早前的，更新后可以了，谢谢

**Comment by nuigdpgf** [comment]
```
Traceback (most recent call last):
  File "/rlhf_chatglm/rlhf/train.py", line 77, in <module>
Traceback (most recent call last):
  File "/rlhf_chatglm/rlhf/train.py", line 77, in <module>
    tokenizer, config, _, _ = dataHelper.load_tokenizer_and_config(tokenizer_class_name=ChatGLMTokenizer,
  File "/usr/local/lib/python3.10/dist-packages/deep_training/data_helper/data_helper.py", line 236, in load_tokenizer_and_config
    tokenizer, config, _, _ = dataHelper.load_tokenizer_and_config(tokenizer_class_name=ChatGLMTokenizer,
  File "/usr/local/lib/python3.10/dist-packages/deep_training/data_helper/data_helper.py", line 236, in load_tokenizer_and_config
    tokenizer = load_tokenizer(tokenizer_name=tokenizer_name or model_args.tokenizer_name,
  File "/usr/local/lib/python3.10/dist-packages/deep_training/data_helper/data_module.py", line 33, in load_tokenizer
    tokenizer = load_tokenizer(tokenizer_name=tokenizer_name or model_args.tokenizer_name,
  File "/usr/local/lib/python3.10/dist-packages/deep_training/data_helper/data_module.py", line 33, in load_tokenizer
    tokenizer = class_name.from_pretrained(tokenizer_name, **tokenizer_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1796, in from_pretrained
    tokenizer = class_name.from_pretrained(tokenizer_name, **tokenizer_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1796, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for '/rlhf_chatglm/convert/pytorch_model.bin'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/rlhf_chatglm/convert/pytorch_model.bin' is the correct path to a directory containing all relevant files for a ChatGLMTokenizer tokenizer.
    raise EnvironmentError(
OSError: Can't load tokenizer for '/rlhf_chatglm/convert/pytorch_model.bin'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/rlhf_chatglm/convert/pytorch_model.bin' is the correct path to a directory containing all relevant files for a ChatGLMTokenizer tokenizer.
```
请问tokenizer 用chatglm的可以吧

**Comment by ssbuild** [comment]
> 

把官方权重文件夹里面关于tokenizer 的词典配置等文件copy到新的权重文件夹即可。

**Comment by nuigdpgf** [comment]
好的，谢谢

**Comment by nuigdpgf** [comment]
```
Some weights of the model checkpoint at /rlhf_chatglm/convert/pytorch_model.bin were not used when initializing ChatGLMForConditionalGeneration: ['transformer.prefix_encoder.embedding.weight']
- This IS expected if you are initializing ChatGLMForConditionalGeneration from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ChatGLMForConditionalGeneration from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Loading checkpoint shards:   0%|                                                                                                                                                      | 0/2 [00:00<?, ?it/s]Killed
```

您好，加载模型时报错了，请问如何解决呢，谢谢

**Comment by ssbuild** [comment]
不是错误吧  ，像是系统内存不足~

**Comment by nuigdpgf** [comment]
2个bin文件为什么会加载很多次呢

**Comment by nuigdpgf** [comment]
![image](https://github.com/ssbuild/rlhf_chatglm/assets/7640706/0a267a7e-bc74-444d-ad32-1c930d060598)
